### ISSUE TITLE
Namespace null does not match expected ""

### ISSUE THREAD

**Issue by vehovsky** [pdvrieze/xmlutil#25] opened 2020-03-16 15:01 UTC
Hi,

not sure what I'm missing but after updating to kotlinx-serialization-runtime 0.20.0 and xmlutil-serialization-jvm 0.20.0.0 (from 0.14.0 and 0.14.0.2). 

Following code:

```kotlin
@Serializable
@XmlSerialName(value = "metadata", namespace = "", prefix = "")
data class Metadata(
    @XmlElement(true)
    val groupId: String = "NONE",
    @XmlElement(true)
    val artifactId: String = "NONE",
    @XmlElement(true)
    val version: String = "NONE"
)

fun main() {

    val response = """<?xml version="1.0" encoding="UTF-8"?>
<metadata>
    <groupId>com.test</groupId>
    <artifactId>test</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</metadata>"""

    val xmlMapperX = XML {
        indent = 4
    }

    println(xmlMapperX.parse(Metadata.serializer(), response))
}

```

Produces:

```java
Exception in thread "main" nl.adaptivity.xmlutil.XmlException: Namespace null does not match expected ""
	at nl.adaptivity.xmlutil.StAXReader.require(StAXReader.kt:113)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$TagDecoder.endStructure(XMLDecoder.kt:748)
	at com.test.Metadata$$serializer.deserialize(XmlTest.kt)
	at com.test.Metadata$$serializer.deserialize(XmlTest.kt:11)
	at nl.adaptivity.xmlutil.serialization.XmlDecoderBase$XmlDecoder.decodeSerializableValue(XMLDecoder.kt:140)
	at nl.adaptivity.xmlutil.serialization.XML.parse(XML.kt:334)
	at nl.adaptivity.xmlutil.serialization.XML.parse(XML.kt:352)
	at com.test.XmlTestKt.main(XmlTest.kt:33)
	at com.test.XmlTestKt.main(XmlTest.kt)
```

**Comment by altavir** [comment] 2020-03-16 15:44
Got the same error in all deserialization tests right now.

**Comment by pdvrieze** [comment] 2020-03-18 13:23
I'll fix this asap. The issue is due to the built in XML format not being compliant to its own specification. "`null`" is not a valid value for namespaces, but is often treated as the `""` namespace. A workaround would be to use woodstox instead.
The problem is that I made the assertion work correctly but didn't check that.

**Comment by altavir** [comment] 2020-03-18 13:34
Are there any workarounds for this? Currently it is a real road blocker.

**Comment by pdvrieze** [comment] 2020-03-20 21:44
The workaround is using woodstox as stax runtime: `runtimeOnly("com.fasterxml.woodstox:woodstox-core:5.0.3")`. I've also pushed a fix to master that should work. Please have a look. I'll try to push it tomorrow - I've been crazy buzy these last days moving all teaching online with 3 days preparation time (including getting to the office to pick up things before we're not supposed to be in the office anymore).

**Comment by altavir** [comment] 2020-03-21 05:42
Thanks, I will try it later today.

**Comment by altavir** [comment] 2020-03-21 13:26
Adding runtime dependency on woodstox helped, thank you.

**Comment by pdvrieze** [comment] 2020-05-17 14:42
Should now work again in 0.20.0.1

**Closed by pdvrieze** 2020-05-17 14:42 UTC
Labels: bug
