### ISSUE TITLE
Error when integrated into android (java) application

### ISSUE THREAD

**Issue by AMBE1203** [pdvrieze/xmlutil#177] opened 2023-09-05 06:09 UTC
This is error: Please suggest me how to fix it 
The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.3.1'. However we cannot choose between the following variants of io.github.pdvrieze.xmlutil:core:0.86.1:

**Comment by pdvrieze** [comment] 2023-09-05 12:09
This is a duplicate of: #89 There are solutions in that issue.

**Closed by pdvrieze** 2023-09-05 12:09 UTC
Labels: duplicate

**Comment by pdvrieze** [comment] 2023-09-07 13:58
In addition, I did a few tests. It seems to work for me (both a fresh android and fresh kotlin project). What versions of gradle/kotlin are you using?
