### ISSUE TITLE
Backend Internal error: Exception during IR lowering

### ISSUE THREAD

**Issue by Kryomancer** [pdvrieze/xmlutil#124] opened 2023-02-27 21:52 UTC
[Full code used here](https://gist.github.com/Kryomancer/39118722a685313f4b4c972ba15b69cb)

When adding a data class to deserialize a tag like `<meaning m_lang="fr">Asie</meaning>` to:

```
                    @Serializable
                    @SerialName("meaning")
                    data class Meaning(
                        @XmlValue
                        val value: String,
                        @XmlElement(false)
                        val m_lang: String?
                    )
```

compilation fails with error `org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering`, [full error log here](https://gist.github.com/Kryomancer/2975dd530709be2c754f21731d00d69f). If I remove this class and instead read the `meaning` tag to 
```
@XmlElement(true)
val meaning: List<String>
```
Instead of a `List<Meaning>` it will compile and work but the obvious problem is that I can no longer access the `m_lang` attribute.

**Comment by pdvrieze** [comment] 2023-02-28 08:39
Unfortunately default annotation parameters still fail to be processed by the plugin in cases of incremental compilation (clean compiles generally work).
It is a duplicate of #81

**Closed by pdvrieze** 2023-02-28 08:39 UTC
Labels: duplicate, cantfix
