### ISSUE TITLE
How can I create a dynamic XML Tag?

### ISSUE THREAD

**Issue by fkrauthan** [pdvrieze/xmlutil#41] opened 2020-09-08 02:47 UTC
I have a usecase where I need to generate one of the tags dynamically. Lets assume I have the following data class:

```
data class Test(val id: String, val entity: MyEntity)
```

I want to have as an potential output an xml that could look like this

```
<Test>
   <Test_123>
       <MyEntityFields... />
   </Test_123>
</Test>
```

Where `Test_123` is the generated tag based on a fixed string and the dynamic value `123` from the `id` field. I also would need to have `MyEntity` NOT have there SerialName printed and instead directly print all there attribute elements.

**Comment by pdvrieze** [comment] 2020-09-09 11:45
If I understand you correctly, the name of the tag is dynamically determined based upon the data. In the case that it is "predictable" you may be able to use the policy together with polymorphism to handle this. Another option would be to use an xml filter that you put between the xml document (XmlReader/XmlWriter) and the serialization format that would transform the name used.

The use of dynamic tag names is not recommended in the use of XML. Tags are not supposed to carry data / be dynamic. The "correct" approach would be to have an id attribute: `<Test id="123">`. An additional point is that you want to "merge" the `Test` and `MyEntity` types. This merging is not supported at this point. The ultimate way in which you could implement this would be with a custom serializer/deserializer where you special case Xml. The serializer has been designed such that it implements the `XmlInput` and `XmlOutput` interfaces that provide access to the underlying xml.

However, the easiest way would probably be to have 2 xml filters (one for reading, one for writing) that live between the serialization framework and the xml parser/serializer. 

While you can use the policy to determine tag names to use, the policy does not provide access to (or use) the underlying data nor could it in case of parsing (it determines the structure before parsing).

**Comment by fkrauthan** [comment] 2020-09-09 18:14
Yeah unfortunately I need to consume an API that requires me todo that. So you suggest to write some generic filter or potential use string replace to prepare the payload/response string?

**Comment by pdvrieze** [comment] 2020-09-28 08:14
I think a filter is the easiest way to go. The other usable solution would be to have a custom serializer for `Test` that looks at the id/xml and then creates a sub-serializer with the needed name that you serialize to the output from the outer serializer (or deserialize from the input). The filters I mean are xml filters (they implement `XmlReader`, but have an underlying reader where the events come from except when filtered/modified - the same for writing).,

**Comment by fkrauthan** [comment] 2020-10-02 05:44
Do you have any example of something like this by any chance?

**Comment by pdvrieze** [comment] 2020-10-10 19:49
You could have a look at: https://github.com/pdvrieze/ProcessManager/blob/ec833120eaeb5749925b59dbe13cbdb2bfdc8171/ProcessEngine/core/src/commonMain/kotlin/nl/adaptivity/process/engine/PETransformer.kt which is a filter where certain tags are replaced by values or other elements. Note that that filter does not involve the serialization framework as it is intended to take xml from a configuration file and substitute values from a database/other context into it.

**Comment by pdvrieze** [comment] 2020-10-18 21:46
I've written an example solution to this. You can find the solution at: https://github.com/pdvrieze/xmlutil/tree/dev/examples/src/main/kotlin/net/devrieze/serialization/examples/dynamictagnames

It is not documented yet. Also note that with the released versions you need to use the compat version. The non-compat version uses some further properties on the `XML.XmlInput` and `XML.XmlOutput` interfaces that allow for new serializers to be created with identical configuration. The example solution uses a custom serializer to hide the magic from users, but still needs filters due to id value as well as other integration limitations. I'll close this when I finished documenting.

**Comment by pdvrieze** [comment] 2020-10-19 11:14
This should now be available in: https://github.com/pdvrieze/xmlutil/blob/master/examples/DYNAMIC_TAG_NAMES.md

**Closed by pdvrieze** 2020-10-19 11:14 UTC
Labels: question

**Comment by fkrauthan** [comment] 2020-10-19 16:54
Perfect thank you. I will give this a try soon.

**Comment by fkrauthan** [comment] 2021-01-18 00:59
Sorry for the super late reply but I had finally time to look at my project again. I started going through your example and it seems like an insane amount of work for something simple as changing the tag name. I was wondering if there is maybe a chance to implement a generic standard solution into the library. Maybe add a new Annotation like `@DynamicSerialName` onto a ether a String attribute or a method that returns a string. And the core XML Framework uses the returned value instead of the Serial Name? This would obviously prevent me (and potentially other people) write a lot of code. Alternative (as that might make deserialization a bit more tricky) adding support for a `Map<String, T>` like Jackson offers `@JsonAnySetter` and `@JsonAnyGetter` that will be called unless an exact match was found.

**Comment by pdvrieze** [comment] 2021-02-01 20:52
@fkrauthan Basically the problem is that what you are trying to parse is not valid xml. It is one of the plenty variants of "almostXml" around. The serialization format basically is designed with the assumption that XML is used in a way consistent with the XML standards and designs (without dynamic tags) - also supporting DTDs and schemas.
As such the sample solution is based around two things:
- Using a filter that "rewrites/rereads" the serialized XML so that the serialization framework sees a conforming XML format.
- Using a custom serializer that intercepts the serialization (when using an xml format) and does serialization/deserialization using this filter. (To make it transparent for users).

A `@DynamicSerialName` would not work as the format needs to be able to do the following: see a tag/attribute name; map that name to an element (from the serial descriptor) (including a list - for which the name must be the same for all list elements). Note that the policy already supports providing the QName used for the tag to be anything you want (but it is called when the tag structure is determined (just before things are actually written).

As an alternative, shorter, way you can still use a custom serializer for the tag that skips the filters and just writes/reads XML directly (rather than letting everything happen through the serializer).

**Comment by fkrauthan** [comment] 2021-02-01 21:01
@pdvrieze I have to disagree. Two XML documents:

```xml
<InitialVersion><Name>Hello</Name></InitialVersion>
```

```xml
<HelloVersion><Name>Hello</Name></HelloVersion>
```

are both 100% valid XML. But I don't want to have to create 50 different data classes to map them so I would like to create a data class like:

```kotlin
data class Version(@DynamicSerialName val tagName: String, val name: String)
```

That can parse both documents with a single data class (this is very simplified of what I am looking at). And similar I want to be able to use this data class to create both versions of XML (by just changing `tagName` from `HelloVersion` to `InitalVersion`).

**Comment by pdvrieze** [comment] 2021-02-01 21:53
Both of them can be valid XML. But given that XML is expected to be used with a DTD there would be a static/limited set of names expected.

However I suspect that your issue is one of code reuse (rather than tag names that contain attribute values). In that case it may be better to use a policy that determines the tag name from the use site (the attribute containing the value) rather than the type:
```
   @Serializable
   data class Version(@SerialName("Name") @XmlElement(true) val name:String)

   @Serializable
   class Foo(
     @SerialName("HelloVersion"
     val helloVersion: Version
    )
```

As to actually having many kind of "version" objects, I would say that just having a serializable `Version` base class with many child classes would probably be the way to go (unless these are actually supposed to be semantically equal). Alternatively, why not go for:
```<Version kind="HelloVersion">Hello</Version>```
XML supports attributes, and you don't need to make the name yet another nested tag. That is the kind of design that gives XML a bad name.

**Comment by pdvrieze** [comment] 2021-02-01 22:03
Btw. the custom deserializer route is not going to be able to work. The reason being that the deserializer for the owner must be able to map a tag name to the child it belongs to (and thus which deserializer to use). As you don't know the deserializer at that point you can't use it.
A key element of the (re)design of the framework is that it now uses the same code to determine the conceptual XML structure for serialization and deserialization. This has removed lots of bugs and complexity, but it does rely on the assumption that the document structure (schema if you will) can be determined fully from the information in the serializer/deserializer and it does not rely on the (dynamic) data written or read.
By far the most straightforward way to handle this (1 kotlin type becomes multiple xml types) is to use (read and write) filters that translate this to an attribute. At the same time, from an xml perspective, why do you really want many tags names that represent the same underlying type?

**Comment by fkrauthan** [comment] 2021-02-03 02:50
Yeah but again the problem is less about if I can define the XML (I wouldn't use XML to begin with) but if I have to generate and/or ingest XML from third parties. And yes my issue is more about code re-use / the dynamic nature of the API I need to conform to where at runtime a new user can be onboarded which requires a different tag (while the rest of the structure stays the same).

**Comment by pdvrieze** [comment] 2021-02-03 10:17
@fkrauthan I'm (too) aware of these braindead uses of XML in "almost xml" formats. I still consider normalizing filters the right way to handle it. I don't consider there to be an issue to make that quite accessible, but to do so isn't really straightforward (in particular if it based upon annotations how to combine filters).
