### ISSUE TITLE
IndexOutOfBoundsException: Index 6 out of bounds for length 6

### ISSUE THREAD

**Issue by ComBatVision** [pdvrieze/xmlutil#118] opened 2023-01-01 01:53 UTC
After update to the latest release 0.84.3 my project starts failing during R8 minification with following error:

AGPBI: {"kind":"error","text":"java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6","sources":[{"file":"/home/suffix/.gradle/caches/transforms-3/91f04056b26ec555b64893802a6678ef/transformed/jetified-xmlutil-android-0.84.3.jar"}],"tool":"R8"}

**Comment by ComBatVision** [comment] 2023-01-01 12:21
Probably issue is not in version update itself, but in conflict with Kotlinx Json serialization library.

This error appears after I added Json library and Kotlin serialization gradle plugin into my project.

I will investigate and write my conclusion.

**Comment by ComBatVision** [comment] 2023-01-01 12:51
Current error appears after adding folloing dependencies to the project:
classpath "org.jetbrains.kotlin:kotlin-serialization:1.7.20"
apply plugin:  'kotlinx-serialization'
implementation"org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"

Could you assist with any conclusions?
Why XML serialization conflicts with JSON?
I have already implemented protobuf dependency and it works Ok. 

![зображення](https://user-images.githubusercontent.com/12487306/210171023-e6f9cc34-6697-42b5-898a-431d77248739.png)

**Comment by ComBatVision** [comment] 2023-01-01 14:22
Adding following pro-guard rule fixes an issue, but it is not OK to exclude whole library from minification.
Could you review pro-guard rules inside library, please. 

# XML util - this rule fixes build issue IndexOutOfBoundsException: Index 6 out of bounds for length 6
-keep class nl.adaptivity.xmlutil.** { *; }

**Comment by pdvrieze** [comment] 2023-01-04 15:57
There seems to be some code that for unclear reasons triggers a bug in r8. I will try to see what I can do, but it is not very clear. Also the library does not need reflection except if you are going into service providers to load alternative parsers.

**Comment by hovadur** [comment] 2023-01-28 17:38
More complete error:
    
    AGPBI: {"kind":"error","text":"java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6","sources":[{"file":"/Users/oleghlystov/.gradle/caches/transforms-3/3539ec3d260f7cd6a74bd88ea13ea3ec/transformed/xmlutil-android-0.84.3.jar"}],"tool":"R8"}
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':android:minifyTstWithR8'.
    > A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
       > Compilation failed to complete, position: Lnl/adaptivity/xmlutil/core/KtXmlReader;next()Lnl/adaptivity/xmlutil/EventType;, origin: /Users/oleghlystov/.gradle/caches/transforms-3/3539ec3d260f7cd6a74bd88ea13ea3ec/transformed/xmlutil-android-0.84.3.jar:nl/adaptivity/xmlutil/core/KtXmlReader.class

**Comment by pdvrieze** [comment] 2023-01-29 10:51
This appears to be a duplicate of #87. It only appears to impact `KtXmlReader` though, so I could try to figure out how to add an automatic proguard rule.

**Comment by pdvrieze** [comment] 2023-01-30 21:11
I have added proguard/r8 files to the artefact that seem to resolve it in #87 (with [rememberwear/53c18835](https://github.com/yschimke/rememberwear/commit/53c188353b9f1a56d62af70ce25e551aaa14ccc1) ), as it now builds the release.

It should be available as snapshot. Please test whether that works.

**Comment by hovadur** [comment] 2023-01-31 06:17
where to get a snapshot?

**Comment by pdvrieze** [comment] 2023-02-01 10:30
There was an unfortunate unrelated bug in the build system to do with native builds (caused by an attempt to fix dependencies between the nativeTest and nativeMain sourcesets in intellij - not an issue for gradle itself). This has now been disabled outside of intellij, so the build now works correctly and the snapshots are available through the published sonatype snapshot repository.

**Comment by pdvrieze** [comment] 2023-02-19 15:34
A custom proguard rule that should fix this is now in [0.85.0](https://github.com/pdvrieze/xmlutil/releases/tag/v0.85.0).

**Closed by pdvrieze** 2023-02-19 15:34 UTC
Labels: duplicate
